[package]
name = "zipf_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = {version = "0.23.4", features = ["extension-module"]}
zipf = "7.0.1"
rand = "0.8.5"

[lib]
crate-type = ["cdylib"]
